function install_allegro(){log("Allegro installed!")}function allegro_init(){install_allegro()}function allegro_init_all(a,b,c,d,e){install_allegro();set_gfx_mode(a,b,c);install_mouse(d);install_keyboard(e);install_sound()}function END_OF_MAIN(){window.addEventListener("load",main)}var mouse_b=0,mouse_pressed=0,mouse_released=0,mouse_x=-1,mouse_y=-1,mouse_z=-1,mouse_mx=0,mouse_my=0,mouse_mz=0,_mouse_installed=!1,_last_mouse_x=-1,_last_mouse_y=-1,_last_mouse_z=-1,_menu=!1;
function install_mouse(a){if(!canvas)return _error("You must call set_gfx_mode before install_mouse"),-1;if(_mouse_installed)return _allog("Mouse already installed"),-1;canvas.canvas.addEventListener("mouseup",_mouseup);canvas.canvas.addEventListener("mousedown",_mousedown);canvas.canvas.addEventListener("mousemove",_mousemove);canvas.canvas.addEventListener("wheel",_mousewheel);a?_menu_supress=!0:(canvas.canvas.addEventListener("contextmenu",_mousemenu),_menu_supress=!1);_mouse_installed=!0;log("Mouse installed!");
return 0}function remove_mouse(){if(!_mouse_installed)return _error("You must call install_mouse before remove_mouse"),-1;canvas.canvas.removeEventListener("mouseup",_mouseup);canvas.canvas.removeEventListener("mousedown",_mousedown);canvas.canvas.removeEventListener("mousemove",_mousemove);canvas.canvas.removeEventListener("wheel",_mousewheel);_menu_supress&&canvas.canvas.removeEventListener("contextmenu",_mousemenu);_mouse_installed=!1;log("Mouse removed!");return 0}
function show_mouse(){if(!_mouse_installed)return _error("You must call install_mouse before show_mouse"),-1;canvas.canvas.style.cursor="auto";return 0}function hide_mouse(){if(!_mouse_installed)return _error("You must call install_mouse before hide_mouse"),-1;canvas.canvas.style.cursor="none";return 0}function _mousemenu(a){a.preventDefault()}function _mouseup(a){mouse_b&=~(1<<a.which-1);mouse_pressed|=1<<a.which-1;a.preventDefault()}
function _mousedown(a){mouse_b|=1<<a.which-1;mouse_released|=1<<a.which-1;a.preventDefault()}function _mousemove(a){mouse_x=a.offsetX;mouse_y=a.offsetY;a.preventDefault()}function _mousewheel(a){mouse_z+=a.deltaY;a.preventDefault()}var _downloadables=[],_installed_timers=[];function _timer_lookup(a){for(var b=0;b<_installed_timers.length;b++)if(_installed_timers[b].timer==a)return _installed_timers[b];return-1}function SECS_TO_TIMER(a){return 1E3*a}function MSEC_TO_TIMER(a){return a}
function BPS_TO_TIMER(a){return 1E3/a}function BPM_TO_TIMER(a){return 6E4/a}function install_timer(){}function time(){return(new Date).getTime()}function install_int(a,b){return install_int_ex(a,MSEC_TO_TIMER(b))}function install_int_ex(a,b){var c=window.setInterval(a,b);_installed_timers.push({timer:a,id:c});log("Added insterrupt #"+c+" at "+b+"msec isntervals!")}var _loopproc;
function _uberloop(){_mouse_installed&&(mouse_mx=mouse_x-_last_mouse_x,mouse_my=mouse_y-_last_mouse_y,mouse_mz=mouse_z-_last_mouse_z);_loopproc();if(_keyboard_installed)for(var a=0;128>a;a++)pressed[a]=!1,released[a]=!1;_mouse_installed&&(mouse_mz=mosue_my=mouse_mx=mouse_released=mouse_pressed=0,_last_mouse_x=mouse_x,_last_mouse_y=mouse_y,_last_mouse_z=mouse_z)}function loop(a,b){_loopproc=a;window.setInterval(_uberloop,b);log("Game loop initialised!")}var _loader_init_time,_ready_proc,_bar_proc;
function _progress_check(){for(var a=0,b=0,c=0;c<_downloadables.length;c++)a++,"snd"==_downloadables[c].type&&_downloadables[c].element.readyState>=_downloadables[c].element.HAVE_FUTURE_DATA&&(_downloadables[c].ready=!0),_downloadables[c].ready&&b++;_bar_proc&&_bar_proc(a/b);b<a?window.setTimeout(_progress_check,100):(log("Loading complete! Took "+((time()-_loader_init_time)/1E3).toFixed(1)+" seconds!"),_ready_proc())}
function loading_bar(a){rectfill(canvas,5,SCREEN_H-55,SCREEN_W-10,50,makecol(0,0,0));rectfill(canvas,10,SCREEN_H-50,SCREEN_W-20,40,makecol(255,255,255));rectfill(canvas,15,SCREEN_H-45,SCREEN_W-30,30,makecol(0,0,0));rectfill(canvas,20,SCREEN_H-40,scaleclamp(a,0,1,0,SCREEN_W-40),20,makecol(255,255,255))}function ready(a,b){_loader_init_time=time();_ready_proc=a;log("Loader initialised!");_bar_proc=b?b:loading_bar;window.setTimeout(_progress_check,100)}
function remove_int(a){for(a=0;a<_installed_timers.length;a++)if(_installed_timers[a].timer==_installed_timers){log("Removing interrupt "+_installed_timers[a].id+"!");window.clearInterval(_installed_timers[a].id);_installed_timers.splice(a,1);break}}function remove_all_ints(){for(var a=0;a<_installed_timers.length;a++)window.clearInterval(_installed_timers[a].id);_installed_timers=[];log("Removed all interrupts!")}
var KEY_A=65,KEY_B=66,KEY_C=67,KEY_D=68,KEY_E=69,KEY_F=70,KEY_G=71,KEY_H=72,KEY_I=73,KEY_J=74,KEY_K=75,KEY_L=76,KEY_M=77,KEY_N=78,KEY_O=79,KEY_P=80,KEY_Q=81,KEY_R=82,KEY_S=83,KEY_T=84,KEY_U=85,KEY_V=86,KEY_W=87,KEY_X=88,KEY_Y=89,KEY_Z=90,KEY_0=48,KEY_1=49,KEY_2=50,KEY_3=51,KEY_4=52,KEY_5=53,KEY_6=54,KEY_7=55,KEY_8=56,KEY_9=57,KEY_0_PAD=96,KEY_1_PAD=97,KEY_2_PAD=98,KEY_3_PAD=99,KEY_4_PAD=100,KEY_5_PAD=101,KEY_6_PAD=102,KEY_7_PAD=103,KEY_8_PAD=104,KEY_9_PAD=105,KEY_F1=112,KEY_F2=113,KEY_F3=114,KEY_F4=
115,KEY_F5=116,KEY_F6=117,KEY_F7=118,KEY_F8=119,KEY_F9=120,KEY_F10=121,KEY_F11=122,KEY_F12=123,KEY_ESC=27,KEY_TILDE=192,KEY_MINUS=189,KEY_EQUALS=187,KEY_BACKSPACE=8,KEY_TAB=9,KEY_OPENBRACE=219,KEY_CLOSEBRACE=221,KEY_ENTER=13,KEY_COLON=186,KEY_QUOTE=222,KEY_BACKSLASH=220,KEY_COMMA=188,KEY_STOP=190,KEY_SLASH=191,KEY_SPACE=32,KEY_INSERT=45,KEY_DEL=46,KEY_HOME=36,KEY_END=35,KEY_PGUP=33,KEY_PGDN=34,KEY_LEFT=37,KEY_RIGHT=39,KEY_UP=38,KEY_DOWN=40,KEY_SLASH_PAD=111,KEY_ASTERISK=106,KEY_MINUS_PAD=109,KEY_PLUS_PAD=
107,KEY_ENTER_PAD=13,KEY_PRTSCR=44,KEY_PAUSE=19,KEY_EQUALS_PAD=12,KEY_LSHIFT=16,KEY_RSHIFT=16,KEY_LCONTROL=17,KEY_RCONTROL=17,KEY_ALT=18,KEY_ALTGR=18,KEY_LWIN=91,KEY_RWIN=92,KEY_MENU=93,KEY_SCRLOCK=157,KEY_NUMLOCK=144,KEY_CAPSLOCK=20,key=[],pressed=[],released=[],_keyboard_installed=!1,_default_enabled_keys=[KEY_F1,KEY_F2,KEY_F3,KEY_F4,KEY_F5,KEY_F6,KEY_F7,KEY_F8,KEY_F9,KEY_F10,KEY_F11,KEY_F12],_enabled_keys=[];
function install_keyboard(a){if(_keyboard_installed)return _allog("Keyboard already installed"),-1;_enabled_keys=a?a:_default_enabled_keys;for(a=0;128>a;a++)key[a]=!1,pressed[a]=!1,released[a]=!1;window.addEventListener("keyup",_keyup);window.addEventListener("keydown",_keydown);_keyboard_installed=!0;log("Keybaord installed!")}
function remove_keyboard(){if(!_keyboard_installed)return _allog("Keyboard not installed"),-1;window.removeEventListener("keyup",_keyup);window.removeEventListener("keydown",_keydown);_keyboard_installed=!1;log("Keybaord removed!")}function _keydown(a){key[a.keyCode]||(pressed[a.keyCode]=!0);key[a.keyCode]=!0;-1==_enabled_keys.indexOf(a.keyCode)&&a.preventDefault()}function _keyup(a){key[a.keyCode]=!1;released[a.keyCode]=!0;-1==_enabled_keys.indexOf(a.keyCode)&&a.preventDefault()}
function BITMAP_OBJECT(a,b,c,d,e,f){}function create_bitmap(a,b){log("Creating bitmap at "+a+" x "+b+"!");var c=document.createElement("canvas");c.width=a;c.height=b;var d=c.getContext("2d");return{w:a,h:b,canvas:c,context:d,ready:!0,type:"bmp"}}
function load_bitmap(a){log("Loading bitmap "+a+"...");var b=new Image;b.src=a;time();var c=document.createElement("canvas"),d=c.getContext("2d"),e={canvas:c,context:d,w:-1,h:-1,ready:!1,type:"bmp"};_downloadables.push(e);b.onload=function(){log("Bitmap "+a+" loaded, size: "+b.width+" x "+b.height+"!");e.canvas.width=b.width;e.canvas.height=b.height;e.context.drawImage(b,0,0);e.w=b.width;e.h=b.height;e.ready=!0};return e}function load_bmp(a){return load_bitmap(a)}
var canvas,_gfx_installed=!1,SCREEN_W=0,SCREEN_H=0,font;function set_gfx_mode(a,b,c){var d=document.getElementById(a);if(!d)return _error("Can't find canvas with id "+a),-1;d.width=b;d.height=c;a=d.getContext("2d");SCREEN_W=b;SCREEN_H=c;canvas={w:b,h:c,canvas:d,context:a,ready:!0};font=create_font("monospace");_gfx_installed=!0;return 0}var PI=3.14159265,PI2=6.2831853,PI_2=1.570796325,PI_3=3.14159265/3,PI_4=.7853981625;function RAD(a){return-a*PI/180}function DEG(a){return 180*-a/PI}
function _fillstyle(a,b){a.context.fillStyle="rgba("+getr(b)+","+getg(b)+","+getb(b)+","+getaf(b)+")"}function _strokestyle(a,b,c){c||(c=1);a.context.lineWidth=c;a.context.strokeStyle="rgba("+getr(b)+","+getg(b)+","+getb(b)+","+getaf(b)+")"}function makecol(a,b,c,d){d||(d=255);return d<<24|(a&255)<<16|(b&255)<<8|c&255}function makecolf(a,b,c,d){d||(d=1);return makecol(255*a,255*b,255*c,255*d)}function getr(a){return a>>16&255}function getg(a){return a>>8&255}function getb(a){return a&255}
function geta(a){return a>>>24}function getrf(a){return a>>16&255}function getgf(a){return a>>8&255}function getbf(a){return a&255}function getaf(a){return(a>>>24)/255}function getpixel(a,b,c){a=a.context.getImageData(b,c,1,1).data;return a[3]<<24|(a[0]&255)<<16|(a[1]&255)<<8|a[2]&255}function putpixel(a,b,c,d){_fillstyle(a,d);a.context.fillRect(b,c,1,1)}function clear_bitmap(a){_fillstyle(a,0);a.context.fillRect(0,0,a.w,a.h)}
function clear_to_color(a,b){_fillstyle(a,b);a.context.fillRect(0,0,a.w,a.h)}function line(a,b,c,d,e,f,g){_strokestyle(a,f,g);a.context.beginPath();a.context.moveTo(b,c);a.context.lineTo(d,e);a.context.stroke()}function vline(a,b,c,d,e,f){f||(f=1);_fillstyle(a,e);a.context.fillRect(b,c,f,d-c)}function hline(a,b,c,d,e,f){f||(f=1);_fillstyle(a,e);a.context.fillRect(b,c,d-b,f)}
function triangle(a,b,c,d,e,f,g,h,k){_strokestyle(a,h,k);a.context.beginPath();a.context.moveTo(b,c);a.context.lineTo(d,e);a.context.lineTo(f,g);a.context.closePath();a.context.stroke()}function trianglefill(a,b,c,d,e,f,g,h){_fillstyle(a,h);a.context.beginPath();a.context.moveTo(b,c);a.context.lineTo(d,e);a.context.lineTo(f,g);a.context.closePath();a.context.fill()}
function polygon(a,b,c,d,e){_strokestyle(a,d,e);a.context.beginPath();for(d=0;d<b;d++)d?a.context.lineTo(c[2*d],c[2*d+1]):a.context.moveTo(c[2*d],c[2*d+1]);a.context.closePath();a.context.stroke()}function polygonfill(a,b,c,d){_fillstyle(a,d);a.context.beginPath();for(d=0;d<b;d++)d?a.context.lineTo(c[2*d],c[2*d+1]):a.context.moveTo(c[2*d],c[2*d+1]);a.context.closePath();a.context.fill()}function rect(a,b,c,d,e,f,g){_strokestyle(a,f,g);a.context.strokeRect(b,c,d,e)}
function rectfill(a,b,c,d,e,f){_fillstyle(a,f);a.context.fillRect(b,c,d,e)}function circle(a,b,c,d,e,f){_strokestyle(a,e,f);a.context.beginPath();a.context.arc(b,c,d,0,PI2);a.context.stroke()}function circlefill(a,b,c,d,e){_fillstyle(a,e);a.context.beginPath();a.context.arc(b,c,d,0,PI2);a.context.fill()}function arc(a,b,c,d,e,f,g,h){_strokestyle(a,g,h);a.context.beginPath();a.context.arc(b,c,f,RAD(d),RAD(e));a.context.stroke()}
function arcfill(a,b,c,d,e,f,g){_fillstyle(a,g);a.context.beginPath();a.context.arc(b,c,f,RAD(d),RAD(e));a.context.fill()}function draw_sprite(a,b,c,d){a.context.drawImage(b.canvas,c,d)}function stretch_sprite(a,b,c,d,e,f){a.context.drawImage(b.canvas,0,0,b.w,b.h,c,d,e,f)}function rotate_sprite(a,b,c,d,e){a.context.save();a.context.translate(c,d);a.context.rotate(RAD(e));a.context.translate(-b.w/2,-b.h/2);a.context.drawImage(b.canvas,0,0);a.context.restore()}
function pivot_sprite(a,b,c,d,e,f,g){a.context.save();a.context.translate(c,d);a.context.rotate(RAD(g));a.context.translate(-e,-f);a.context.drawImage(b.canvas,0,0);a.context.restore()}function rotate_scaled_sprite(a,b,c,d,e,f){a.context.save();a.context.translate(c,d);a.context.rotate(RAD(e));a.context.translate(-f*b.w/2,-f*b.h/2);a.context.drawImage(b.canvas,0,0,b.w,b.h,c,d,b.w*f,b.h*f);a.context.restore()}
function pivot_scaled_sprite(a,b,c,d,e,f,g,h){a.context.save();a.context.translate(c,d);a.context.rotate(RAD(g));a.context.translate(-h*e,-h*f);a.context.drawImage(b.canvas,0,0,b.w,b.h,c,d,b.w*h,b.h*h);a.context.restore()}function blit(a,b,c,d,e,f,g,h){b.context.drawImage(a.canvas,c,d,g,h,e,f,g,h)}function stretch_blit(a,b,c,d,e,f,g,h,k,l){b.context.drawImage(a.canvas,c,d,e,f,g,h,k,l)}var _num_fonts=0;function FONT_OBJECT(a,b,c,d){}
function load_font(a){var b=document.createElement("style"),c="font"+_num_fonts++;b.id=c;b.type="text/css";document.head.appendChild(b);b.textContent="@font-face { font-family: "+c+"; src:url('"+a+"');}";return{element:b,file:a,name:c,type:"fnt"}}function create_font(a){return{element:null,file:"",name:a,type:"fnt"}}
function textout(a,b,c,d,e,f,g,h,k){a.context.font=f.toFixed()+"px "+b.name;a.context.textAlign="left";_fillstyle(a,g);a.context.fillText(c,d,e);h&&(_strokestyle(a,h,k),a.context.strokeText(c,d,e))}function textout_centre(a,b,c,d,e,f,g,h,k){a.context.font=f.toFixed()+"px "+b.name;a.context.textAlign="center";_fillstyle(a,g);a.context.fillText(c,d,e);h&&(_strokestyle(a,h,k),a.context.strokeText(c,d,e))}
function textout_right(a,b,c,d,e,f,g,h,k){a.context.font=f.toFixed()+"px "+b.name;a.context.textAlign="right";_fillstyle(a,g);a.context.fillText(c,d,e);h&&(_strokestyle(a,h,k),a.context.strokeText(c,d,e))}var _volume=1,_samples=[];function SAMPLE_OBJECT(a,b,c,d,e){}function install_sound(){}function set_volume(a){_volume=a;for(a=0;a<_samples.length;a++)_samples[a].element.volume=_samples[a].volume*_volume}function get_volume(){return _volume}
function load_sample(a){var b=document.createElement("audio");b.src=a;var c={element:b,file:a,volume:1,ready:!1,type:"snd"};_downloadables.push(c);_samples.push(c);log("Loading sample "+a+"...");b.onloadeddata=function(){c.ready||(c.ready=!0,log("Sample "+a+" loaded!"))};return c}function destroy_sample(a){}function play_sample(a,b,c,d){b||0==b||(b=1);c||0==c||(c=1);d||(d=!1);adjust_sample(a,b,c,d);a.element.currentTime=0;a.element.play()}
function adjust_sample(a,b,c,d){a.volume=b;a.element.volume=a.volume*_volume;a.element.loop=d;a.element.playbackRate=c}function stop_sample(a){a.element.pause();a.element.currentTime=0}function pause_sample(a){a.element.pause()}function rand(){return Math.floor(65536*Math.random())}function rand32(){return rand()|rand()<<16}function frand(){return Math.random()}function abs(a){return 0>a?-a:a}function length(a,b){return Math.sqrt(a*a-b*b)}
function distance(a,b,c,d){return Math.sqrt((c-a)*(c-a)+(d-b)*(d-b))}function distance2(a,b,c,d){return(c-a)*(c-a)+(d-b)*(d-b)}function linedist(a,b,c,d,e,f){c-=a;d-=b;var g=((e-a)*c+(f-b)*d)/(c*c+d*d);1<g?g=1:0>g&&(g=0);a=a+g*c-e;b=b+g*d-f;return Math.sqrt(a*a+b*b)}function lerp(a,b,c){return a+(b-a)*c}function dot(a,b,c,d){return a*c+b*d}function sgn(a){return 0>a?-1:0<a?1:0}function angle(a,b,c,d){a=DEG(Math.atan2(d-b,c-a));return 0>a?a+360:a}
function anglediff(a,b){var c;c=(b-a)/360;c=360*(c-floor(c));180<c&&(c-=360);return c}function clamp(a,b,c){return c>b?a<b?b:a>c?c:a:a<c?c:a>b?b:a}function scale(a,b,c,d,e){return d+(a-b)/(c-b)*(e-d)}function scaleclamp(a,b,c,d,e){a=d+(a-b)/(c-b)*(e-d);if(e>d)return a=a<e?a:e,a>d?a:d;a=a<d?a:d;return a>e?a:e}var _debug_enabled=!1,_debug_element,ALLEGRO_CONSOLE=!1;function _error(a){log("[ERROR] "+a);alert(a)}
function enable_debug(a){(_debug_element=document.getElementById(a))&&(_debug_enabled=!0)}function log(a){ALLEGRO_CONSOLE&&console&&console.log(a);_debug_enabled&&(_debug_element.innerHTML=_debug_element.innerHTML+a+"<br/>")}function wipe_log(){_debug_enabled&&(_debug_element.innerHTML="")};
